---
name: Tests

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rubocop_and_matrix:
    runs-on: ubuntu-24.04
    outputs:
      ruby: ${{ steps.ruby.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
      - id: ruby
        uses: voxpupuli/ruby-version@v1

  unit:
    needs: rubocop_and_matrix
    name: "Unit tests ${{ matrix.ruby }} ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025]
        ruby: ${{ fromJSON(needs.rubocop_and_matrix.outputs.ruby) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Output Ruby Environment
        run: bundle env
      - name: Cache modules
        id: modules
        uses: actions/cache@v4
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - name: Unit tests
        run: bundle exec rake tests:unit

  run-dita:
    runs-on: ubuntu-24.04

    steps:
    - name: Initialize
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Generate docs
      run: bundle exec rake docs:all
    - name: Docs test
      uses: dita-ot/dita-ot-action@4.1.2
      with:
        build: dita -i documentation/bolt.ditamap -o out -f html5 --processing-mode=strict

  local_transports:
    name: "local transport ${{ matrix.ruby }} ${{ matrix.os }}"
    needs: rubocop_and_matrix
    env:
      BOLT_WINRM_USER: roddypiper
      BOLT_WINRM_HOST: localhost
      BOLT_WINRM_PORT: 5985
      BOLT_WINRM_SSL_PORT: 5986
      BOLT_WINRM_SMB_PORT: 445
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025]
        ruby: ${{ fromJSON(needs.rubocop_and_matrix.outputs.ruby) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache modules
        id: modules
        uses: actions/cache@v4
        with:
          path: modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/Puppetfile') }}
      - name: Install modules
        if: steps.modules.outputs.cache-hit != 'true'
        run: bundle exec r10k puppetfile install
      - if: matrix.os == 'ubuntu-24.04'
        uses: ./.github/actions/sudo_setup
      - if: matrix.os == 'windows-2025'
        uses: ./.github/actions/windows_agent_setup
      - if: matrix.os == 'ubuntu-24.04'
        name: Run tests
        run: bundle exec rake ci:local_transport:linux
      - if: matrix.os == 'windows-2025'
        name: Run tests
        run: bundle exec rake ci:local_transport:windows

  tests:
    needs:
      - rubocop_and_matrix
      - unit
      - run-dita
      - local_transports
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - run: echo Test suite complete
